version: '3.4'

services:
  go:
    container_name: go-api-server
    platform: linux/x86_64
    hostname: localhost
    ports:
      - 2345:2345 #　デバッグ用のポート
    tty: true
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./back:/go/src/app
